# Generated by Django 5.2.3 on 2025-06-19 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
