# Generated by Django 5.2.3 on 2025-07-20 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theatre_app', '0002_alter_performance_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='performance',
            unique_together={('theatre', 'title', 'date', 'time')},
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.RemoveField(
            model_name='performance',
            name='description',
        ),
        migrations.RemoveField(
            model_name='performance',
            name='duration_minutes',
        ),
        migrations.RemoveField(
            model_name='performance',
            name='ticket_price',
        ),
    ]
